### ISSUE TITLE
Message and Mailbox Documentation

### ISSUE THREAD

**Issue by t-walker-21** [t-walker-21/CS321-JTK#4]
Hello @Joanna-G , I've merged your branch with Master  #2  and closed/deleted that branch. Now I just need you to go through and comment our code.

**Comment by t-walker-21** [comment]
@Joanna-G  I guess the documentation doesn't have to be great a this stage, but Dr. Li does want your Name at the top at the code

**Comment by Joanna-G** [comment]
Still figuring out how all this works and the best way I do that is just clicking on stuff. I'll get it in a minute, I promise.

**Comment by t-walker-21** [comment]
I completely understand. It is tricky to get down!

**Comment by t-walker-21** [comment]
Just saw the commit, great work. I will gather all these files into one workspace project and zip it for Thursday.
